# -*- coding: utf-8 -*-
from . import account_move
from . import establecimiento
#from . import configuracion_rubros
from . import res_company
from . import comprobante_electronico_factura
from . import ats
from . import res_partner
from . import account_tax_group
from . import account_journal
from . import account_retention
from . import account_guia_remision
from . import account_move_reversal
from . import inventario_servicios
from . import bitacora_consumo_web_service
from . import comprobante_electronico_retencion
from . import comprobante_electronico_guia_remision
from . import comprobante_electronico_nota_credito
from . import comprobante_electronico_nota_debito
from . import comprobante_electronico_retencion
from . import comprobante_electronico_liquidacion_compra
from . import account_liquidacion_compra
from . import tipo_proveedor_reembolso
from . import account_payment
#from . import contrato_estado_cuenta_pagos
#from . import reporte_ventas
#from . import reporte_prospecto
#from . import pago_cuotas